//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.15 at 12:56:57 PM EDT 
//


package org.cvrgrid.philips.jaxb.beans;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www3.medical.philips.com}statementcomponents" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "statementcomponents"
})
@XmlRootElement(name = "interpretationdatastructure")
public class Interpretationdatastructure {

    protected Statementcomponents statementcomponents;

    /**
     * Gets the value of the statementcomponents property.
     * 
     * @return
     *     possible object is
     *     {@link Statementcomponents }
     *     
     */
    public Statementcomponents getStatementcomponents() {
        return statementcomponents;
    }

    /**
     * Sets the value of the statementcomponents property.
     * 
     * @param value
     *     allowed object is
     *     {@link Statementcomponents }
     *     
     */
    public void setStatementcomponents(Statementcomponents value) {
        this.statementcomponents = value;
    }

}
